#!/usr/bin/env bash
# precommit_audit.sh — content-level credential scan for olist-lakehouse
# Run from repo root before every `git push`.
#
# Exit code 0 = safe to push. Non-zero = fix and re-run.
#
# Generated by notebooks/phase_8/03_pre_commit_audit.py.

set -uo pipefail
fail=0

echo "== Pre-commit audit =="

# ---- Check 1: staged-diff credential patterns ----
# We grep the *staged* diff specifically (`--cached`) because that's
# what's about to be committed. Unstaged changes can be inspected
# separately with a manual `git diff`.

if git diff --cached | grep -qi 'dapi'; then
  echo "❌ FAIL: Databricks PAT (dapi…) found in staged diff"
  fail=1
else
  echo "✅ no dapi tokens in staged diff"
fi

if git diff --cached | grep -qE 'private_key|private_key_id'; then
  echo "❌ FAIL: GCP service account key markers found in staged diff"
  fail=1
else
  echo "✅ no GCP key markers in staged diff"
fi

if git diff --cached | grep -qE '(ghp_|gho_|ghs_|xoxb-|xoxp-|AKIA)[A-Za-z0-9]{16,}'; then
  echo "❌ FAIL: third-party token (GitHub/Slack/AWS) found in staged diff"
  fail=1
else
  echo "✅ no third-party tokens in staged diff"
fi

# ---- Check 2: working-tree files that shouldn't exist ----

if find . -name '.databrickscfg' -not -path './.git/*' | grep -q .; then
  echo "❌ FAIL: .databrickscfg exists in working tree"
  fail=1
else
  echo "✅ no .databrickscfg in working tree"
fi

# JSON files outside the allow-list — REVIEW (warn, don't fail)
unexpected_json=$(find . -name '*.json' -not -path './.git/*' \
  -not -name 'package.json' -not -name 'package-lock.json' \
  -not -name 'tsconfig.json' 2>/dev/null)
if [ -n "$unexpected_json" ]; then
  echo "⚠️  REVIEW: unexpected JSON files (verify non-sensitive):"
  echo "$unexpected_json" | sed 's/^/      /'
else
  echo "✅ no unexpected JSON files"
fi

# ---- Check 3: databricks.yml inline token ----

if [ -f databricks.yml ]; then
  if grep -qE '^[[:space:]]*token:' databricks.yml; then
    echo "❌ FAIL: inline 'token:' in databricks.yml"
    fail=1
  else
    echo "✅ no inline token in databricks.yml"
  fi
else
  echo "ℹ️  databricks.yml not present (skipping that check)"
fi

# ---- Summary ----

echo ""
if [ "$fail" -eq 0 ]; then
  echo "✅ PASS — safe to push"
  echo "   Recommended: also run 'git diff --cached' for an eyeball review"
  exit 0
else
  echo "❌ FAIL — fix issues above before pushing"
  echo "   See RECOVERY_RUNBOOK.md if a credential was already committed"
  exit 1
fi
